/**
 * Mock data for the Portfolio AI app
 * Realistic Indian market data
 */

export const MOCK_HOLDINGS = [
  {
    id: 'h1',
    symbol: 'RELIANCE.NS',
    name: 'Reliance Industries',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Energy',
    quantity: 25,
    avgPrice: 2450.00,
    currentPrice: 2892.35,
    previousClose: 2870.10,
    dayHigh: 2905.00,
    dayLow: 2865.20,
    week52High: 3025.00,
    week52Low: 2220.00,
    addedDate: '2024-06-15',
  },
  {
    id: 'h2',
    symbol: 'TCS.NS',
    name: 'Tata Consultancy',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Technology',
    quantity: 15,
    avgPrice: 3600.00,
    currentPrice: 3945.60,
    previousClose: 3980.25,
    dayHigh: 3990.00,
    dayLow: 3920.00,
    week52High: 4250.00,
    week52Low: 3300.00,
    addedDate: '2024-03-20',
  },
  {
    id: 'h3',
    symbol: 'HDFCBANK.NS',
    name: 'HDFC Bank',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Banking',
    quantity: 40,
    avgPrice: 1520.00,
    currentPrice: 1685.40,
    previousClose: 1675.80,
    dayHigh: 1695.00,
    dayLow: 1670.00,
    week52High: 1800.00,
    week52Low: 1400.00,
    addedDate: '2024-01-10',
  },
  {
    id: 'h4',
    symbol: 'INFY.NS',
    name: 'Infosys',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Technology',
    quantity: 30,
    avgPrice: 1400.00,
    currentPrice: 1578.90,
    previousClose: 1590.45,
    dayHigh: 1595.00,
    dayLow: 1565.00,
    week52High: 1700.00,
    week52Low: 1250.00,
    addedDate: '2024-05-05',
  },
  {
    id: 'h5',
    symbol: 'ICICIBANK.NS',
    name: 'ICICI Bank',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Banking',
    quantity: 50,
    avgPrice: 950.00,
    currentPrice: 1125.75,
    previousClose: 1118.30,
    dayHigh: 1135.00,
    dayLow: 1112.00,
    week52High: 1200.00,
    week52Low: 880.00,
    addedDate: '2024-02-18',
  },
  {
    id: 'h6',
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    exchange: 'Crypto',
    sector: 'Cryptocurrency',
    quantity: 0.15,
    avgPrice: 3800000.00,
    currentPrice: 5825000.00,
    previousClose: 5780000.00,
    dayHigh: 5900000.00,
    dayLow: 5750000.00,
    week52High: 6200000.00,
    week52Low: 2800000.00,
    addedDate: '2024-04-12',
  },
  {
    id: 'h7',
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    exchange: 'Crypto',
    sector: 'Cryptocurrency',
    quantity: 2.5,
    avgPrice: 185000.00,
    currentPrice: 265000.00,
    previousClose: 262000.00,
    dayHigh: 270000.00,
    dayLow: 258000.00,
    week52High: 320000.00,
    week52Low: 150000.00,
    addedDate: '2024-07-01',
  },
  {
    id: 'h8',
    symbol: 'PPFAS-MF',
    name: 'Parag Parikh Flexi Cap Fund',
    type: 'mutualfund',
    exchange: 'MF',
    sector: 'Diversified',
    quantity: 500,
    avgPrice: 58.50,
    currentPrice: 72.35,
    previousClose: 72.10,
    dayHigh: 72.50,
    dayLow: 71.80,
    week52High: 78.00,
    week52Low: 52.00,
    addedDate: '2023-11-20',
  },
  {
    id: 'h9',
    symbol: 'NIFTY-ETF',
    name: 'Nippon India Nifty 50 ETF',
    type: 'etf',
    exchange: 'NSE',
    sector: 'Index',
    quantity: 100,
    avgPrice: 210.00,
    currentPrice: 238.50,
    previousClose: 237.00,
    dayHigh: 240.00,
    dayLow: 236.00,
    week52High: 250.00,
    week52Low: 195.00,
    addedDate: '2024-08-05',
  },
  {
    id: 'h10',
    symbol: 'AXISBANK.NS',
    name: 'Axis Bank',
    type: 'stock',
    exchange: 'NSE',
    sector: 'Banking',
    quantity: 35,
    avgPrice: 1050.00,
    currentPrice: 1178.25,
    previousClose: 1170.50,
    dayHigh: 1185.00,
    dayLow: 1165.00,
    week52High: 1250.00,
    week52Low: 950.00,
    addedDate: '2024-09-15',
  },
];

export const MOCK_GOALS = [
  {
    id: 'g1',
    name: 'Retirement Corpus',
    icon: '🏖️',
    targetAmount: 50000000,
    currentAmount: 3245000,
    monthlyContribution: 50000,
    targetDate: '2045-01-01',
    expectedReturn: 12,
    priority: 'high',
    createdDate: '2024-01-01',
  },
  {
    id: 'g2',
    name: 'House Down Payment',
    icon: '🏠',
    targetAmount: 3000000,
    currentAmount: 1250000,
    monthlyContribution: 30000,
    targetDate: '2028-06-01',
    expectedReturn: 10,
    priority: 'high',
    createdDate: '2024-03-15',
  },
  {
    id: 'g3',
    name: 'Emergency Fund',
    icon: '🛡️',
    targetAmount: 600000,
    currentAmount: 420000,
    monthlyContribution: 15000,
    targetDate: '2026-12-31',
    expectedReturn: 7,
    priority: 'medium',
    createdDate: '2024-06-01',
  },
  {
    id: 'g4',
    name: 'Dream Vacation',
    icon: '✈️',
    targetAmount: 500000,
    currentAmount: 85000,
    monthlyContribution: 10000,
    targetDate: '2027-03-01',
    expectedReturn: 8,
    priority: 'low',
    createdDate: '2025-01-10',
  },
];

export const MOCK_ALERTS = [
  {
    id: 'a1',
    type: 'critical',
    category: 'portfolio',
    title: 'Portfolio dropped 3.2% today',
    message: 'Your portfolio lost ₹45,200 today due to a broad market selloff. Tech and banking sectors led the decline.',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    actionable: true,
    action: 'View Portfolio',
  },
  {
    id: 'a2',
    type: 'warning',
    category: 'allocation',
    title: 'Banking sector overweight detected',
    message: 'Banking stocks make up 38% of your portfolio. Consider diversifying to reduce sector concentration risk.',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    read: false,
    actionable: true,
    action: 'View Rebalancing',
  },
  {
    id: 'a3',
    type: 'info',
    category: 'goal',
    title: 'Emergency Fund is 70% complete!',
    message: 'Great progress! At your current SIP rate, you\'ll reach your Emergency Fund goal by August 2026.',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: true,
    actionable: false,
  },
  {
    id: 'a4',
    type: 'warning',
    category: 'rebalance',
    title: 'Time to rebalance your portfolio',
    message: 'Your portfolio has drifted 8% from target allocation. Consider rebalancing for optimal risk-adjusted returns.',
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    read: true,
    actionable: true,
    action: 'Rebalance Now',
  },
  {
    id: 'a5',
    type: 'info',
    category: 'insight',
    title: 'Reliance hit 52-week high',
    message: 'RELIANCE.NS reached ₹2,905 today, approaching its 52-week high of ₹3,025. Consider booking partial profits.',
    timestamp: new Date(Date.now() - 259200000).toISOString(),
    read: true,
    actionable: false,
  },
];

export const ASSET_TYPE_COLORS = {
  stock: '#3b82f6',
  crypto: '#8b5cf6',
  mutualfund: '#10b981',
  etf: '#f59e0b',
};

export const ASSET_TYPE_LABELS = {
  stock: 'Stocks',
  crypto: 'Crypto',
  mutualfund: 'Mutual Funds',
  etf: 'ETFs',
};

export const SECTOR_COLORS = {
  'Technology': '#3b82f6',
  'Banking': '#10b981',
  'Energy': '#f59e0b',
  'Cryptocurrency': '#8b5cf6',
  'Diversified': '#06b6d4',
  'Index': '#ec4899',
  'Other': '#64748b',
};

export const STOCK_SEARCH_DATA = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', type: 'stock', sector: 'Energy', exchange: 'NSE' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', type: 'stock', sector: 'Technology', exchange: 'NSE' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', type: 'stock', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'INFY.NS', name: 'Infosys', type: 'stock', sector: 'Technology', exchange: 'NSE' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', type: 'stock', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', type: 'stock', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'ITC.NS', name: 'ITC Limited', type: 'stock', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', type: 'stock', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', type: 'stock', sector: 'Telecom', exchange: 'NSE' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', type: 'stock', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', type: 'stock', sector: 'Infrastructure', exchange: 'NSE' },
  { symbol: 'WIPRO.NS', name: 'Wipro', type: 'stock', sector: 'Technology', exchange: 'NSE' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', type: 'stock', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', type: 'stock', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', type: 'stock', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma', type: 'stock', sector: 'Pharma', exchange: 'NSE' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', type: 'stock', sector: 'Conglomerate', exchange: 'NSE' },
  { symbol: 'TITAN.NS', name: 'Titan Company', type: 'stock', sector: 'Consumer', exchange: 'NSE' },
  { symbol: 'BTC', name: 'Bitcoin', type: 'crypto', sector: 'Cryptocurrency', exchange: 'Crypto' },
  { symbol: 'ETH', name: 'Ethereum', type: 'crypto', sector: 'Cryptocurrency', exchange: 'Crypto' },
  { symbol: 'SOL', name: 'Solana', type: 'crypto', sector: 'Cryptocurrency', exchange: 'Crypto' },
  { symbol: 'DOGE', name: 'Dogecoin', type: 'crypto', sector: 'Cryptocurrency', exchange: 'Crypto' },
  { symbol: 'XRP', name: 'Ripple', type: 'crypto', sector: 'Cryptocurrency', exchange: 'Crypto' },
  { symbol: 'PPFAS-MF', name: 'Parag Parikh Flexi Cap Fund', type: 'mutualfund', sector: 'Diversified', exchange: 'MF' },
  { symbol: 'AXIS-MF', name: 'Axis Bluechip Fund', type: 'mutualfund', sector: 'Large Cap', exchange: 'MF' },
  { symbol: 'MIRAE-MF', name: 'Mirae Asset Large Cap Fund', type: 'mutualfund', sector: 'Large Cap', exchange: 'MF' },
  { symbol: 'NIFTY-ETF', name: 'Nippon India Nifty 50 ETF', type: 'etf', sector: 'Index', exchange: 'NSE' },
  { symbol: 'GOLDBEES', name: 'Nippon India Gold ETF', type: 'etf', sector: 'Commodity', exchange: 'NSE' },
];
